### PR TITLE
Geco curve bonding script

### PR DESCRIPTION
**Pull request by sethfork**

### CODE REVIEW

**Comment by dOrgJelli** [comment]
What was the purpose of the build script instead of just using truffle directly?

**Comment by dOrgJelli** [comment]
Also as a personal opinion, I don't like having project specific scripts in the root level package.json. I can understand a "build all" or "test all" script, but having ones specific to the bonding curve project seems messy IMO.

**Comment by dOrgJelli** [comment]
Also I don't see prettier being used anywhere, but it's installed everywhere. Was the intention to add a commit hook?

**Comment by sethfork** [comment]
The purpose of the build script is to export plain JavaScript instead of JSON, which is the default output of truffle migrations. This will make it easier for library consumers / users to import and manipulate ABIs from DAOfeatures.

This PR is incomplete at the moment. I've yet to add the prettier commit hook, as well as some additional cleanups / placement. I'm with you on the build/test all script.

**Comment by dOrgJelli** [comment]
prettier - sounds good.
root package.json - sounds good.
JS ABIs - I'm kinda conflicted on this. I don't like making the assumption that ABI consumers will be using javascript, and if you are using javascript couldn't you achieve the same functionality the build script does by doing this:
```javascript
const abi = require("./path/to/abi/contract.abi").abi;
```

**Comment by dOrgJelli** [comment]
whoops sorry, just looked at the output, I think it'd be equivalent to just doing:
```javascript
const abi = require("./path/to/abi/contract.json");
```

**Comment by dOrgJelli** [comment]
Let's bring these changes into the geco-milestone-1 branch @sethfork

**Pull request closed without merging**
