### PR TITLE
Layout Refactor: Still WIP

### PR DESCRIPTION
**Pull request by dOrgJelli**
Lots of groundwork and documentation still needs to be done, but wanted to PR this in to get some feedback.

### CODE REVIEW

**Comment by sogasg** [comment]
Templates are templates for creating DAOs, with a set of features and configuration for those features, right?

I think we have to find a new name for the repo (not DAOfeatures or DAOtemplates) but something that encapsulates both. Or split it up into DAOtemplates and DAOfeatures. Features can be used in templates, but custom DAOs can also use them.

And I think maybe that Utilities should live under features (they are feature utilities).

**Comment by dOrgJelli** [comment]
Definitely agree @sogasg, I'll rename this repo back to DAOfeatures, and move the templates to a DAOtemplates repo.

**Comment by oshimony** [comment]
@dOrgJelli I really like the layout refactor, but I think that we should keep them all in one repo. Features and templates accomplish the same thing at different granularities correct? If I want more customizability or a blank slate I utilize individual features but if I want to start from a template I go with that.

Separating them would add unnecessary complexity to the toolchain IMO. Do you agree?

**Comment by sethfork** [comment]
Big fan of the move to a lerna monorepo. As for the package architecture, I find flat monorepo package folders to be the easiest to reason about, from both a contributor's perspective, and as a consumer of the packages/library - at least in the short term.

**Comment by dOrgJelli** [comment]
> Big fan of the move to a lerna monorepo. As for the package architecture, I find flat monorepo package folders to be the easiest to reason about, from both a contributor's perspective, and as a consumer of the packages/library - at least in the short term.

So in this case @sethfork would the "features" and "utilities" folders go away, and everything would be at the top level?

**Comment by dOrgJelli** [comment]
> @dOrgJelli I really like the layout refactor, but I think that we should keep them all in one repo. Features and templates accomplish the same thing at different granularities correct? If I want more customizability or a blank slate I utilize individual features but if I want to start from a template I go with that.
> 
> Separating them would add unnecessary complexity to the toolchain IMO. Thoughts?

I can definitely see this as well... need to think on this more. @sogasg any thoughts?

**Comment by sogasg** [comment]
I think a monorepo is good too. We just need a suitable name for the repo.

Conceptually, I think this is what we have:
- DAOfeatures
- DAOvotingMachines (perhaps in the future)
- DAOfeature configurations (parameters like voting machine etc.)
- DAOtemplates - a set of DAOfeature configurations

It might make sense to call if DAOfeatures? I am not sure.

But, I do not understand why there would not be sperate folders for features and templates

**Comment by dOrgJelli** [comment]
Okay awesome, so it looks like we're converging a bit. I'm going to make the decision to have DAOfeatures and DAOtemplates be separate repos for the time being, and we can combine them if it makes some things easier like for instance testing.

The topology can shift as we develop this all further.

**Comment by dOrgJelli** [comment]
@sogasg @sethfork @oshimony could you sign off on this if it sits well with you?

**Pull request merged**
